/// Flutter icons UnitsIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UnitsIcons
///      fonts:
///       - asset: fonts/UnitsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UnitsIcons {
  UnitsIcons._();

  static const _kFontFam = 'UnitsIcons';

  static const IconData volume = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData temperature = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData weight = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData length = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData currency = const IconData(0xe80c, fontFamily: _kFontFam);
}
